-- auto Generated on 2019-04-11 17:54:32 
-- DROP TABLE IF EXISTS `pig001`; 
CREATE TABLE pig001(
    `id` INTEGER(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
    `age` INTEGER(12) NOT NULL DEFAULT -1 COMMENT 'age',
    `name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'name',
    PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'pig001';
